on:
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: corretto
          cache: maven
          server-id: ossrh # Value of distributionManagement.repository.id field of pom.xml
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          settings-path: ${{ github.workspace }} # Location for settings.xml file
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE

      - name: Check settings.xml file
        run: cat ${{ github.workspace }}/settings.xml
